puke: fix bug

diff --git a/puke b/puke
--- a/puke
+++ b/puke
@@ -69,7 +69,7 @@ pkg_checksum() {
         esac
 
         (cd "${src_path%/*}" >/dev/null
-         sha256sum -- "${src##*/}" || die "Failed to generate checksums.")
+         sha256sum "${src##*/}" || die "Failed to generate checksums.")
     done < sources > "${1-checksums}"
 }
 
